version: '3.8'
services:
web:
build:
context: .
dockerfile: Dockerfile
container_name: traffic-sign-fastapi
ports:
- "7001:7001"
volumes:
- .:/app
environment:
- PYTHONUNBUFFERED=1
- PYTHONDONTWRITEBYTECODE=1
restart: always