services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic-sign-fastapi
    ports:
      - "7001:8000"
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 7001 --reload
